Use generalized parseQC approach + RnaSeq QC metrics
smaht-dac/qc-pipelines pull request #3
Opened 2023-10-18 15:15 UTC by alexander-veit

The RnaSeq QC metrics pipeline still needs some adjustments.

Also the `bamstats` script has been added. We might not use it though.

2023-10-19 20:34 UTC, B3rse requested changes

2023-10-19 20:34 UTC, B3rse commented on descriptions/parseQCs_BamQM.cwl
> +      prefix: "--metrics samtools"
I think this should be samtools_stats, we may have other samtools commands in the future that we need to parse, such as flagstat for example

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/bamstats/Dockerfile
> +    locales=2.35-0ubuntu3.1 \
this version is giving me some problems, I removed the version and getting the last one in all the other dockers. They removed this specific one or something but wasn't building anymore for me

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/bamstats/Dockerfile
> +    locales=2.35-0ubuntu3.1 \
```suggestion
    locales \
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/parseQCs_BamQM.cwl
>    - id: qmtype
```suggestion
  - id: qm_name
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/parseQCs_BamQM.cwl
> +      prefix: "--metrics samtools"
```suggestion
      prefix: "--metrics samtools_stats"
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/parseQCs_BamQM.cwl
> +    Run parse-qc to generate BamQM quality metrics
```suggestion
    Run parse-qc to generate BAM quality metrics
```

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/parseqc/Dockerfile
```suggestion
```

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/parseqc/Dockerfile
> +## Python dependencies
```suggestion
## Install qc-parser
```

2023-10-19 20:34 UTC, B3rse commented on portal_objects/workflows/bamstats.yaml
> +  out:
```suggestion
  output_file_txt:
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/bamstats.cwl
> +  - id: out
```suggestion
  - id: output_file_txt
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/bamstats.cwl
> +  - id: input_bam
```suggestion
  - id: input_file_bam
```

2023-10-19 20:34 UTC, B3rse commented on portal_objects/workflows/bamstats.yaml
> +  input_bam:
```suggestion
  input_file_bam:
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/bamstats.cwl
> +  - id: genome_size
```suggestion
  - id: effective_genome_size
```

2023-10-19 20:34 UTC, B3rse commented on portal_objects/workflows/bamstats.yaml
> +  genome_size:
```suggestion
  effective_genome_size:
```

2023-10-19 20:34 UTC, B3rse commented on descriptions/bamstats.cwl
> +  - id: input_bam
I am trying to keep a convention across all pipelines where if it is a file I am specifying file_<format>, so it is a bit more standard

2023-10-19 20:34 UTC, B3rse commented on descriptions/bamstats.cwl
> +    doc: Genome size used to calculate coverage
```suggestion
    doc: Effective genome size used to calculate coverage
```

2023-10-19 20:34 UTC, B3rse commented on portal_objects/workflows/bamstats.yaml
> +description: Run bamstats.py script
```suggestion
description: Run bamStats.py script to calculate quality metrics for input file in BAM format
```

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/bamstats/bamStats.py
I think probably we should keep in pipeline-scripts repo and pull it from the Docker

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/bamstats/run.sh
Is there a reason we need this wrapper instead of calling the command line directly from CWL? I am happy to move the script around in case and move this to the CWL directly, so it's more compact

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/bamstats/Dockerfile
> +FROM smaht/ubuntu2204-py38:0.0.1
```suggestion
FROM public.ecr.aws/smaht-dac/base-ubuntu2204-py38:0.0.1
```

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/rnaseqc/Dockerfile
> +FROM smaht/ubuntu2204-py38:0.0.1
```suggestion
FROM public.ecr.aws/smaht-dac/base-ubuntu2204-py38:0.0.1
```

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/rnaseqc/Dockerfile
> +    locales=2.35-0ubuntu3.1 \
```suggestion
    locales \
```

2023-10-19 20:34 UTC, B3rse commented on dockerfiles/rnaseqc/collect_rnaseqc_metrics.py
maybe also this should go in pipeline-scripts

2023-10-20 15:50 UTC, alexander-veit commented on dockerfiles/bamstats/run.sh
I removed the wrapper.

2023-10-20 15:51 UTC, alexander-veit commented
I made all the suggested changes. Maybe we can move the two scripts to `pipeline-scripts` at a later point.

2023-10-23 18:24 UTC, B3rse requested changes

2023-10-23 18:24 UTC, B3rse commented on descriptions/bamstats.cwl
> +baseCommand: [python bamStats.py]
```suggestion
baseCommand: [python, bamStats.py]
```

2023-10-23 18:24 UTC, B3rse commented on descriptions/bamstats.cwl
> +
```suggestion
```

2023-10-23 18:24 UTC, B3rse commented on descriptions/parseQCs_BamQM.cwl
> +baseCommand: ["parse-qc"]
```suggestion
baseCommand: [parse-qc]
```

2023-10-23 18:24 UTC, B3rse commented on dockerfiles/bamstats/Dockerfile
> +
```suggestion
## bamStats
```

2023-10-23 18:24 UTC, B3rse commented on dockerfiles/parseqc/Dockerfile
```suggestion
```

2023-10-23 18:24 UTC, B3rse commented on dockerfiles/parseqc/Dockerfile
```suggestion
```

2023-10-23 18:24 UTC, B3rse commented on dockerfiles/rnaseqc/Dockerfile
> +
```suggestion
## collect_rnaseqc_metrics run
```

2023-10-23 18:34 UTC, merged